config/routes.rb
Calendar::Application.routes.draw do
  devise_for :users
  resources :events
  get "event/new"
  root to: 'static_pages#home'
  match '/events/(/:id)' => 'calendar#events'
  match '/add_event' => 'calendar#add_event'
  get "calendar/index"
  get "static_pages/home"
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  
  get "calendar/add_event"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
  attr_accessible :email, :name, :start_at, :end_at, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :daily, :all_days, :weekly,
  :biweekly, :monthly, :quarterly, :half_year, :annually

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/calendar_controller.rb
 class CalendarController < ApplicationController
   
   before_filter :signed_in_user
   
   def signed_in_user
     unless signed_in?
       store_location
       redirect_to root_path
     end
   end
   def store_location
     session[:return_to] = request.url
   end
   
 def index
 
 
 
 #@event = Event.new
 #@event.name = "If my email is asdf@asdf.com, then this is correct."
 #@event.email = "bob@bob.com"
 #@event.start_at = Time.now
 #@event.end_at = Time.now
 
 #@event.save

 
   
 @month = (params[:month] || Time.zone.now.month).to_i
 @year = (params[:year] || Time.zone.now.year).to_i
 @shown_month = Date.civil(@year, @month)
 @event_strips = Event.where('email' => current_user.email).event_strips_for_month(@shown_month)

 
 end
   
   def events
     @event = Event.all
   end   

 end


=begin
  def new
    @event = Event.new
  end
  def index
    @event = Event.all
  end
  def create
    @event = Event.new(params[:event])
    @event.save
    redirect_to root_path
  end  
=end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
     before_filter :signed_in_user
   
   def signed_in_user
     unless signed_in?
       store_location
       redirect_to root_path
     end
   end
   def store_location
     session[:return_to] = request.url
   end

  def new
    @event = Event.new
  end
  def index
    @event = Event.all
  end
  def create
    @event = Event.new(params[:event])
    @event.email = current_user.email
    @event.save
    redirect_to root_path
  end
  def update
    @event = Event.find(params[:id])
    @event.update_attributes(params[:test])
    redirect_to root_path
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def show
    #@event = Event.find(params[:id])
    @event = Event.find(params[:id])
    
    if @event.email == current_user.email
    else
      @event = Event.new
      @event.name = "You suck.  You cheater."
      end
    
    
    
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/calendar_helper.rb
module CalendarHelper
def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end

  def event_calendar_options
    {
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"
    }
  end

  def event_calendar
    calendar event_calendar_options do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end
end 

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/calendar/add_event.html.erb
<h1>Add an Event</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@event) do |f| %>
<%= form_tag(:controller => "posts", :action => "create") do %> 
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<%= label_tag :name %>
<%= text_field_tag :name %>

<form action="/../events"><input type="submit"></form>

app/views/calendar/add_events.html.erb
<h1>Add an Event</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@event) do |f| %>
<%= form_tag(:controller => "posts", :action => "create") do %> 
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<%= label_tag :name %>
<%= text_field_tag :name %>

<form action="/../events"><input type="submit"></form>

app/views/calendar/events.html.erb
<h1>hi</h1>

<%= form_tag do %>
  <%= check_box_tag(:pet_dog) %>
<%= label_tag(:pet_dog, "I own a dog") %>
<%= check_box_tag(:pet_cat) %>
<%= label_tag(:pet_cat, "I own a cat") %>

<%= radio_button_tag(:age, "child") %>
<%= label_tag(:age_child, "I am younger than 21") %>
<%= radio_button_tag(:age, "adult") %>
<%= label_tag(:age_adult, "I'm over 21") %>

<%= text_area_tag(:message, "Hi, nice site", :size => "24x6") %>
<%= password_field_tag(:password) %>
<%= hidden_field_tag(:parent_id, "5") %>
<%= search_field(:user, :name) %>
<%= telephone_field(:user, :phone) %>
<%= url_field(:user, :homepage) %>
<%= email_field(:user, :address) %>

<%= select_date Date.today, :prefix => :start_date %>
<% end %>

<form action="/../add_events"><input type="submit"></form>

app/views/calendar/index.html.erb
<% if !user_signed_in? %>
<script type="text/javascript">
window.location = "../static_pages/home"
</script>
<% else %>
<%= stylesheet_link_tag "event_calendar" %>
<%= javascript_include_tag "event_calendar" %>

<%= raw(event_calendar) %>
<%end%>

app/views/events/new.html.erb
<h1>Add an Event</h1>

<div class="row">
    <%= form_for(@event) do |f| %>
      	
      	
      	<div align="center">
      	
  <div class="field">
    <%= f.label :name_of_event %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.date_select :start_at, :start_year => 1950, :order => [:month, :day, :year], :end_year => 2100%>
  </div>
<div class="field">
    <%= f.label :end_at %><br />
    <%= f.date_select :start_at, :start_year => 1950, :order => [:month, :day, :year], :end_year => 2100%>
  </div>
  
  <table cellpadding="15">
<tr>
	<td>
<div class="field">
    <%= f.label(:m) %>
    <%= f.check_box(:monday)%>
  </div>
  </td>
  <td>
<div class="field">
    <%= f.label(:t) %>
    <%= f.check_box(:tuesday)%>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label(:w) %>
    <%= f.check_box(:wednesday)%>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label(:th) %>
    <%= f.check_box(:thursday)%>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label(:f) %>
    <%= f.check_box(:friday)%>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label(:sa) %>
    <%= f.check_box(:saturday)%>
  </div>
  </td>
  <td>
  <div class="field">
    <%= f.label(:s) %>
    <%= f.check_box(:sunday)%>
  </div>
  </td>
</tr>
</table>

<div class="field">
    <%= f.label :end_at %><br />
    <%= f.date_select :start_at, :start_year => 1950, :order => [:month, :day, :year], :end_year => 2100%>
  </div>

      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <% end %>
    <button class="btn btn-large btn-danger" onclick="window.location='../calendar/index'">Cancel</button>


</div>
<!--
<%= button_to 'Cancel', root_path, :class => 'btn btn-large btn-danger' %>
-->
</div>

app/views/events/show.html.erb
<%=@event.id%>
<%=@event.name%>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Calendar", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">


        	<% if user_signed_in? %>
        	<li><%= link_to current_user.email, ""%></li>
        	
        	
        	<li><%= link_to "Make a new event", new_event_path%></li>
        	<% end %>
        	<li><%= link_to "Home", root_path%></li>

  <% if user_signed_in? %>
  <li>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    </li>
  <% else %>
  <li>
    <%= link_to "Sign up", new_user_registration_path %> 
    </li>
  <% end %>

          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= stylesheet_link_tag "application", media: "all", 
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
<body>
	

<% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<%= render 'layouts/header' %>
    <div class="container">
<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
<script type="text/javascript">
window.location = "../calendar"
</script>
	
<% else %>

	<body>
	  
	<h2>Sign in</h2>
<%= form_for("user", :url => user_session_path) do |f| %>
  <p><%= f.label :email %></p>
  <p><%= f.text_field :email %></p>

  <p><%= f.label :password %></p>
  <p><%= f.password_field :password %></p>

  <% if devise_mapping.rememberable? -%>
    <p><%= f.check_box :remember_me %> <%= f.label :remember_me %></p>
  <% end -%>

  <p><%= f.submit "Sign in" %></p>


</body>
<%end%>
<% end -%>